import fs from "fs-extra";
import path from "path";
import { AppConfig } from "./extractAppConfig.js";

export async function generateRootLayout(
  appDir: string,
  config: AppConfig,
  options: { dryRun?: boolean; useTypeScript: boolean }
): Promise<boolean> {
  const extension = options.useTypeScript ? "tsx" : "js";
  const layoutPath = path.join(appDir, `layout.${extension}`);
  const layoutJsPath = path.join(appDir, "layout.js");

  if (fs.existsSync(layoutPath) || fs.existsSync(layoutJsPath)) {
    return false; // Already exists
  }

  const cssImports = config.globalCssImports.join("\n");
  const providersComment =
    config.providers.length > 0
      ? `\n  {/* ${config.providers.join(", ")} */}\n`
      : "";

  // Font Injection
  const fontImports = config.fonts.map((f) => f.import).join("\n");
  const fontDecls = config.fonts.map((f) => f.declaration).join("\n");
  const fontClasses = config.fonts
    .map((f) => `\${${f.variableName}.className}`)
    .join(" ");

  const htmlAttrs = config.htmlAttributes ? ` ${config.htmlAttributes}` : "";
  let bodyAttrs = config.bodyAttributes ? ` ${config.bodyAttributes}` : "";

  if (fontClasses) {
    if (bodyAttrs.includes("className=")) {
      bodyAttrs = bodyAttrs.replace(
        /className=(["'])(.*?)\1/,
        `className={\`$2 ${fontClasses}\`}`
      );
    } else {
      bodyAttrs += ` className={\`${fontClasses}\`}`;
    }
  }

  // Default to lang="en" if not present in attributes
  let finalHtmlAttrs = htmlAttrs;
  if (!finalHtmlAttrs.includes("lang=")) {
    finalHtmlAttrs = ` lang="en"${finalHtmlAttrs}`;
  }

  const content = `import React from 'react';
${fontImports}
${cssImports}

${fontDecls}

export const metadata = {
  title: 'Next.js App',
  description: 'Generated by next-page-to-app-converter',
};

export default function RootLayout({
  children,
}${options.useTypeScript ? ": {\n  children: React.ReactNode;\n}" : ""}) {
  return (
    <html${finalHtmlAttrs}>
      <body${bodyAttrs}>${providersComment}
        {children}
      </body>
    </html>
  );
}
`;

  if (options.dryRun) {
    return true; // Simulate creation
  }

  await fs.ensureDir(appDir);
  await fs.writeFile(layoutPath, content);

  return true;
}
